[package]
name = "leptos_styling_example"
version = "0.1.0"
edition = "2024"

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { version = "0.8.2", features = ["csr"] }
leptos_styling = { version = "0.2.0", features = ["csr"] }
